blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.create_post, name='create')
]

django_ajax/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Post


def create_post(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')

        if title:
            Post.objects.create(title=title, description=description)
            message = f'Post {title} created successfully'
            return JsonResponse({"response": message})
    return render(request, 'blog/create_post.html')

blog/templates/blog/create_post.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>HowToSendDjangoFormWithAjax</title>

</head>
<body>

<hr>
<div>
    <div>
        <h2 style="margin-left:500px;margin-top: 20px">DjangoFormAjax</h2>
    </div>

</div>
<hr>


<div class="container pt-5">

    <div id="my_div">

    </div>

    <form method="POST" id="post-form">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" id="title" placeholder="Title" required>
        </div>
        <div class="form-group">
            <textarea class="form-control" id="description" placeholder="Description" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>


</div>

</body>
<script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script>
    $(document).on('submit', '#post-form', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "blog:create" %}',
            data: {
                title: $('#title').val(),
                description: $('#description').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success: function (json) {
                document.getElementById('post-form').reset()
                Swal.fire(
                    'Good job!',
                    json['response'],
                    'success'
                )
                {#$('#my_div').html('<div class="alert alert-success">' + json['response'] + '</div>')#}
            }
        });
    });
</script>

</html>